import "./assets/css/bootstrap.min.css";
import "./assets/css/animate.css";
import "./assets/css/dataTables.bootstrap4.min.css";
import "./assets/plugins/fontawesome/css/fontawesome.min.css";
import "./assets/plugins/fontawesome/css/all.min.css";
import "./assets/css/style.css";
// js
import "./assets/js/jquery-3.6.0.min.js";
import "./assets/js/feather.min.js";
import "./assets/js/jquery.slimscroll.min.js";
import "./assets/js/jquery.dataTables.min.js";
import "./assets/js/dataTables.bootstrap4.min.js";
import "./assets/js/bootstrap.bundle.min.js";
import "./assets/plugins/apexchart/apexcharts.min.js";
import "./assets/plugins/apexchart/chart-data.js";
